---
- name: Onboarding A Homie
  hosts: all
  become: yes
  vars:
    nfsmounts:
      - { path: "/mnt/andromeda", src: "192.168.1.126:/mnt/galaxy/Andromeda"}
  tasks:
    - name: Install NFS, Git, and Other Important Things
      apt:
        pkg:
          - git
          - nfs-common
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
    
    - name: Mount NFS share
      mount: 
        fstype: nfs
        opts: defaults
        dump: 0
        passno: 0
        state: mounted
        src: "{{item.src}}"
        path: "{{item.path}}"
      with_items: "{{nfsmounts}}"

    - name: Install htop
      apt:
        pkg:
          - htop
          
    

