---
version: "3.3"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - SERVERURL=auto #determines public IP and assigns
      - SERVERPORT=51820 #optional
      - PEERS=1 #optional
      - PEERDNS=192.168.1.1 #optional
      - INTERNAL_SUBNET=192.168.1.0 #optional
    volumes:
      - /home/ubuntu/Documents/workflowFiles/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped