version: "3.3"
services:
# ----------------------------------------------------------------
    influxdb:
        image: influxdb:latest
        ports:
            - '8086:8086'
        volumes:
          - influxdb-storage:/home/nick/Documents/influxdb
        environment:
          - INFLUXDB_DB=db0
          - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
          - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}
      grafana:
        image: grafana/grafana:latest
        ports:
          - '3000:3000'
        volumes:
          - grafana-storage:/home/nick/Documents/grafana
          - ./grafana-provisioning/:/etc/grafana/provisioning
        depends_on:
          - influxdb
        environment:
          - GF_SECURITY_ADMIN_USER=${GRAFANA_USERNAME}
          - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD}
